# Generated by Django 3.2.24 on 2024-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
